version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - yum update
        #      - sudo amazon-linux-extras install java-openjdk11
      - yum install -y maven
  build:
    commands:
      - mvn package
artifacts:
  files:
    - target/*.war


      #artifacts:
      #  discard-paths: yes
      #  files:
      #    - target/*.war
      #    - scripts/*
      #    - appspec.yml

