version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      #      - yum update -y
        #      - sudo amazon-linux-extras install java-openjdk11
      - yum install -y maven
  build:
    commands:
      - mvn package
artifacts:
  files:
    - target/gs-*.jar


      #artifacts:
      #  discard-paths: yes
      #  files:
      #    - target/*.war
      #    - scripts/*
      #    - appspec.yml

